version: '3'
services:

  wildfly:
    image: jboss/wildfly:24.0.0.Final
    ports:
      - "8080:8080"
    volumes:
      - ./deployments:/opt/jboss/wildfly/standalone/deployments
    depends_on:
      - mysql
    environment:
      - JTA_DATASOURCE=java:jboss/datasources/myzkapp
      - DATABASE_URL=jdbc:mysql://mysql:3306/myzkapp
      - DATABASE_DRIVER=com.mysql.cj.jdbc.Driver
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=user

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=myzkapp
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    volumes:
      - ./mysql-data:/var/lib/mysql

  liquibase:
    image: liquibase/liquibase:latest
    depends_on:
      - mysql
    volumes:
      - ./src/main/resources/liquibase:/liquibase/changelog
    command:
      - --driver=com.mysql.cj.jdbc.Driver
      - --url=jdbc:mysql://mysql:3306/myzkapp
      - --changeLogFile=/liquibase/changelog/changelog.xml
      - update
